#!/usr/bin/env python3

from __future__ import annotations

import re
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
MANIFEST_PATH = REPO_ROOT / "scripts" / "data" / "asset-manifest.js"
SKYBLOG_PATH = REPO_ROOT / "scripts" / "data" / "generated-skyblog-pack.js"
OUTPUT_PATH = REPO_ROOT / "scripts" / "data" / "generated-extra-assets.js"


def parse_manifest_files(path: Path) -> dict[str, set[str]]:
    text = path.read_text(encoding="utf-8")
    result: dict[str, set[str]] = {}
    for section in ("backgrounds", "stickers", "frames", "watermarks"):
        match = re.search(rf'{section}: withSrc\("{section}", \[(.*?)\]\)', text, re.S)
        if not match:
            result[section] = set()
            continue
        files = set(re.findall(r'\["[^"]+",\s*"[^"]+",\s*"([^"]+)"\]', match.group(1)))
        result[section] = files
    return result


def parse_generated_rows(path: Path) -> dict[str, set[str]]:
    text = path.read_text(encoding="utf-8")
    return {
        "stickers": set(re.findall(r'generatedSkyblogStickers = \[(.*?)\];', text, re.S)[0].splitlines()),
        "frames": set(re.findall(r'generatedSkyblogFrames = \[(.*?)\];', text, re.S)[0].splitlines()),
    }


def parse_generated_files(path: Path) -> dict[str, set[str]]:
    text = path.read_text(encoding="utf-8")
    stickers = set(re.findall(r'\["[^"]+",\s*"[^"]+",\s*"([^"]+)"\]', re.search(r'generatedSkyblogStickers = \[(.*?)\];', text, re.S).group(1)))
    frames = set(re.findall(r'\["[^"]+",\s*"[^"]+",\s*"([^"]+)"\]', re.search(r'generatedSkyblogFrames = \[(.*?)\];', text, re.S).group(1)))
    return {
        "stickers": stickers,
        "frames": frames,
        "backgrounds": set(),
        "watermarks": set(),
    }


def humanize(stem: str) -> str:
    parts = re.split(r"[_-]+", stem)
    return " ".join(part.capitalize() for part in parts if part)


def make_id(prefix: str, relative_file: str) -> str:
    stem = Path(relative_file).stem.lower()
    stem = re.sub(r"[^a-z0-9]+", "-", stem).strip("-")
    return f"{prefix}-{stem}"


def collect_extras() -> dict[str, list[tuple[str, str, str]]]:
    known_manifest = parse_manifest_files(MANIFEST_PATH)
    known_generated = parse_generated_files(SKYBLOG_PATH)
    collected: dict[str, list[tuple[str, str, str]]] = {}

    for section in ("backgrounds", "stickers", "frames", "watermarks"):
        actual_files = sorted(
            path.relative_to(REPO_ROOT / "assets" / section).as_posix()
            for path in (REPO_ROOT / "assets" / section).rglob("*")
            if path.is_file()
        )
        known_files = known_manifest.get(section, set()) | known_generated.get(section, set())
        extras = [file for file in actual_files if file not in known_files]
        prefix = {"backgrounds": "bg-extra", "stickers": "sticker-extra", "frames": "frame-extra", "watermarks": "wm-extra"}[section]
        collected[section] = [(make_id(prefix, file), humanize(Path(file).stem), file) for file in extras]

    return collected


def render_rows(name: str, rows: list[tuple[str, str, str]]) -> str:
    body = ",\n".join(f'  ["{asset_id}", "{label}", "{file}"]' for asset_id, label, file in rows)
    return f"export const {name} = [\n{body}\n];\n"


def main() -> None:
    rows = collect_extras()
    OUTPUT_PATH.write_text(
        "// Generated by scripts/tools/sync_extra_assets.py\n\n"
        + render_rows("generatedExtraBackgrounds", rows["backgrounds"])
        + "\n"
        + render_rows("generatedExtraStickers", rows["stickers"])
        + "\n"
        + render_rows("generatedExtraFrames", rows["frames"])
        + "\n"
        + render_rows("generatedExtraWatermarks", rows["watermarks"]),
        encoding="utf-8",
    )
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
